### ISSUE TITLE
The Gexf file without having soft return at the end of ">"

### ISSUE THREAD

**Issue by timothyyonglijiang** [francesco-ficarola/gexf4j#16]
Hey Francesco-ficarola,

I tried to use your example to generate a gexf file. However, I found that there is no soft or hard return at the end of ">" in the generated gexf file which makes reading the file very difficult. 
How to solve this problem. 

Thanks.

Tim

**Comment by seinecle** [comment]
+1 on this question! :-)

**Comment by francesco-ficarola** [comment]
Fixed it! With the new release, the XML files are written in pretty printing mode. You can download the new version from the maven central repository.
