### ISSUE TITLE
get Node by id?

### ISSUE THREAD

**Issue by seinecle** [francesco-ficarola/gexf4j#18]
Hi,
At the moment I get a particular node by calling graph.getNodes() and then looping through it until I find the particular node.

Can there be a better way where the node could be identified directly? Something like

Node n = graph.getNodes().get(String nodeId)

Thanks!

**Comment by francesco-ficarola** [comment]
I'm going to work on it, thank you.

**Comment by francesco-ficarola** [comment]
Sorry for the wait, it's a very busy period. Anyway, I created the `getNode(String id)` method. It will be available in the next release of gexf4j. Thank you for your contribution.

**Comment by seinecle** [comment]
Thanks a lot!


On Wed, Oct 7, 2015 at 5:49 PM, Francesco Ficarola <notifications@github.com

**Comment by francesco-ficarola** [comment]
The 1.0.0 version has been released. You can download it from the maven central repository.
