### ISSUE TITLE
node.getAllEdges() returns 0 edges?

### ISSUE THREAD

**Issue by 7yl4r** [francesco-ficarola/gexf4j#19]
I've decided to compare the output of `node.getEdges()` against `node.getAllEdges()`. I was expecting to find that `getEdges` yields outgoing edges (for directed graphs), and `getAllEdges` yields both outgoing and incoming connections. What I found, however, was that `getAllEdges` seems to return 0 edges, incoming or outgoing. Below is a minimal test which demonstrates the issue. Am I doing something wrong or is `getAllEdges` not working? It seems that perhaps a `Node` does not actually implement the `HasNodes` interface. 

```java
    @Test
    public void testGetAllEdges() {
        Gexf gexf = new GexfImpl();
        Graph graph = gexf.getGraph();

        Node in = graph.createNode("in");
        Node middle = graph.createNode("middle");
        Node out = graph.createNode("out");

        in.connectTo(middle);
        middle.connectTo(out);

        List<Edge> edges = middle.getAllEdges();
        Assert.assertEquals(2, edges.size());
    }
```

result: 
```
Expected :2
Actual   :0
```

**Comment by francesco-ficarola** [comment]
Thank you for your post. I'll check as soon as possible.

**Comment by francesco-ficarola** [comment]
Ok, I've checked your issue. Thanks for your time and sorry for the wait. `getAllEdges()` called from a `node` object returns the list of sub-edges belonging to the set of sub-nodes of that node, while `getEdges()` returns the list of out-going edges of that node. For instance:

    Node in = graph.createNode("in");
    Node middle = graph.createNode("middle");
    Node out = graph.createNode("out");
    
    in.connectTo("edge1", middle);
    middle.connectTo("edge2", out);

    List<Edge> edges = middle.getEdges();
    for(Edge edge : edges) {
        System.out.println("Edge ID: " + edge.getId());
    }

The code above will print `Edge ID: edge2`.

Now, suppose you want to create a set of sub-nodes and connect them:

    Node submiddle1 = middle.createNode("submiddle1");
    Node submiddle2 = middle.createNode("submiddle2");
    submiddle1..connectTo("subedge", submiddle2);
    
    List<Edge> edges = middle.getAllEdges();
    for(Edge edge : edges) {
        System.out.println("Sub-Edge ID: " + edge.getId());
    }

This second part of code will print `Sub-Edge ID: subedge`.

Hope this example help you to better understand the difference between the two methods.

Let me know if everything is now clear or if you have any other doubt.

**Comment by 7yl4r** [comment]
I'd forgotten that nodes can have sub-nodes. I suppose this makes perfect sense given that. Thanks for your helpful response!
